# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    aws.region = '<your AWS region of choice eg. us-west-2>'

    aws.instance_type = "<your instance type of choice. eg. t2.micro>"

    aws.keypair_name = "<your AWS ssh keypair name of the public that logs you into aws instances: eg. sshKey>"

    aws.security_groups = ["<your AWS Security group ID>", "<another of your AWS Security group ID; you can have an array of just one SG id>"]

    #Select the AMI to use with Vagrant
    aws.region_config "us-west-2", :ami => "ami-01f05461"   # hvm:ebs-ssd Ubuntu 14.04.5 LTS from Canonical's AWS account
    
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "<your AWS public ssh keypair that logs you into aws instances: eg. /path/to/sshKey.pem>"

    aws.tags = {
      'Name' => '<name your instance something you can quickly search for in AWS: eg. Made this with chef!>'
    }

  end

  config.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = "../../chef/cookbooks"
    chef.nodes_path = "nodes"
    chef.roles_path = "roles"
    chef.add_role "node"
  end

end